### ISSUE TITLE
Corner of the option is not rounded in Windows 11

### ISSUE THREAD

**Issue by TheSilvered** [krlvm/AcrylicMenus#19] opened 2022-11-13 18:12 UTC
![immagine](https://user-images.githubusercontent.com/78680412/201537433-a75c7e7b-2fd7-4267-898b-34083875c465.png)

**Comment by krlvm** [comment] 2022-11-13 20:08
Duplicate of #13

**Closed by krlvm** 2022-11-13 20:08 UTC
