### ISSUE TITLE
Bad font rendering under high transparency

### ISSUE THREAD

**Issue by nullnullnullnull0** [krlvm/AcrylicMenus#1] opened 2021-11-07 16:21 UTC
If the transparency of SetWindowCompositionAttribute is increased, the defects of font rendering will be very obvious.
![2021 11 07_19 12 56](https://user-images.githubusercontent.com/21099726/140653012-6d41faf3-1921-40f9-b725-fdc6f4aaa0fd.png)

Is it possible to get the same font rendering as StartAllBack?
![OePXSbx](https://user-images.githubusercontent.com/21099726/140653022-53818dbe-4ce9-4f55-8442-2c53bd941653.png)

**Comment by krlvm** [comment] 2021-11-07 17:53
As I mentioned in release notes, this application is more like a concept and is not ready to daily use.

The cause of poor font rendering is using `SetWindowLong` with `LWA_COLORKEY`, which makes all gray pixels transparent, while, some pixels has other shades of gray due to ClearType antialiasing.

So, to fix this, we need to find another way to make context menu background transparent - this will also fix the delay and flickering before applying blur effect.

**Comment by valinet** [comment] 2021-11-08 07:29
Please use `SetWindowLongPtr`, I assume you are developing on and for `amd64`, so you should use that.

Adding the `WS_EX_LAYERED` extended window style and calling `SetLayeredWindowAttributes` with `LWA_COLORKEY` is not necessarily the way to go: besides changing window properties that shouldn't really be changed, it sets just a single color as "transparent", yielding the poor rendering demonstrated above.

You shouldn't do that, probably. And I think you did it because you got bad font rendering without, like:

![image](https://user-images.githubusercontent.com/6503598/140699334-3955e991-d0fd-43b7-aa49-e6e8e0df7b35.png)

That's normal - text is probably drawn with `DrawTextW`; GDI does not know about transparency, so it leaves the alpha untouched, so probably set to 0 if the hDC is initialized to 0. That means transparent. When the brush is finally added, the color components are considered to be premultiplied with the alpha, so that's why you get a slight hint of color, but nothing proper. What you should do is go and manually correct all the pixels of the text, and make sure they have a correct alpha, probably 1 for where the letter is drawn, but maybe even less than 1 but not 0 for the edges, idk. It's a pretty monumental task. Fortunately, the theme functions have a replacement fro `DrawTextW`: `DrawThemeTextEx`. You supply that with the `DTT_COMPOSITED` flag and that will draw antialiased text on a hDC with a 32-bit top-down DIB section attached to it. That's what i sue to draw text in the properties GUI of EP, or in the window switcher.

For everything else you might want to draw, the alpha has to be fixed. If you want to draw something solid, no need to adjust the color as well, since if alpha is 1, 1 times something is something, so the colors would be the same. In my window switcher, there is an implementation of `FrameRect` but that draws with proper alpha, for example (using `StretchDIBits`): https://github.com/valinet/sws/blob/master/SimpleWindowSwitcher/sws_WindowSwitcher.c#L601 

Doing this properly is not THAT easy... Also, if hooking just Explorer, which I'd recommend, hooking via some other method would be preferable, like sub classing.

The acrylic backdrop brush is simply a bit slow. Even SAB's menus are slower than unskinned menus. Mica is a lighter effect. I had a similar problem, in the Windows 10 window switcher, let's say, with acrylic, in that it is a touch too slow sometimes; for me, I anyway hide the window, so it was slow only the first time, plus that the way it is implemented now, the window is initially cloaked until 200ms pass, so if the user hits `Alt`+`Tab` quickly, the window does not appear and disappear quickly, so during that cloak period it also has time to generate and apply the brush, so it is hardly noticeable. But I experienced it as well.

Also, another observation: don't do this:

```
HOOKPROC hHookProc = (HOOKPROC)GetProcAddress(hDLL, "?CallWndProc@@YA_JH_K_J@Z");
```

Instead, decorate `CallWndProc` using `extern "C"` and it will get exported using its actual name, without any C++ decorations:

```
extern "C" {
    __declspec(dllexport) LRESULT CALLBACK CallWndProc(int nCode, WPARAM wParam, LPARAM lParam) { ... }
}
```

Or, just code in C ;)

This is interesting, but pretty hard to do right. Maybe taking a look on StartAllBack can offer you some better insight. Anyway, good start and keep up the good work!

**Comment by krlvm** [comment] 2021-11-08 11:17
Thanks for all the valuable advice, I really appreciate it because I don't have much experience with C / WinAPI. I will try to implement them.
Thanks a lot again!

**Comment by krlvm** [comment] 2022-04-04 22:58
Partially fixed in [version 0.5](https://github.com/krlvm/AcrylicMenus/releases/tag/v0.5), as seen in the video above

**Comment by krlvm** [comment] 2022-07-09 03:55
Great, this is much better, although some artifacts are still visible. 

I've determined how does StartAllBack do this, it subclasses the context menu before painting and hooks into DrawThemeBackground.

IIRC we also discussed re-implementing SAB accent colorization, I've managed to complete it.

**Comment by nullnullnullnull0** [comment] 2022-07-09 04:18
The TranslucentFlyouts project also hooked the tooltip, but it has no rounded corners. StartAllBack's tooltip has rounded corners. Maybe using DWMWA_WINDOW_CORNER_PREFERENCE ? But the StartAllBack's tooltip does not have a 1px border. Usually, Using DWMWA_WINDOW_CORNER_PREFERENCE will have 1
px border.

**Comment by krlvm** [comment] 2022-07-09 04:26
SAB injects directly into the File Explorer process and hooks almost all methods related to reading theme data and low-level drawing

**Comment by nullnullnullnull0** [comment] 2022-07-09 04:33
Why does sab draw the right-click menu without removing the border, but using DWMWA_BORDER_COLOR to set a white border? Why not remove the border directly like the tooltip.

**Comment by krlvm** [comment] 2022-07-30 18:44
I've released [version 1.0.0] [based on](https://github.com/ALTaleX531/TranslucentFlyouts/issues/5) TranslucentFlyouts, which fixes the font rendering issues.

**Closed by krlvm** 2022-07-30 18:44 UTC
Labels: bug

**Comment by nullnullnullnull0** [comment] 2022-07-31 03:00
Better than TranslucentFlyouts, opens the menu faster. Would you consider disabling Immersive Menu, this fixes the weird menu width.

**Comment by krlvm** [comment] 2022-07-31 11:03
To disable immersive menus you just need to remove ownerdraw flag via SetMenuInfo hook
